name: Build and Push Container

on:
    push:
        branches:
            - master
            - dev
        tags:
            - "v*"
    workflow_dispatch:

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ghcr.io/arewelazeryet/stabledeath

jobs:
    docker:
        strategy:
            fail-fast: false
            max-parallel: 2
            matrix:
                include:
                    - runner: ubuntu-24.04
                      platform: linux/amd64
                      tag_suffix: x86_64
                    - runner: ubuntu-24.04-arm
                      platform: linux/arm64
                      tag_suffix: arm64
        runs-on: ${{ matrix.runner }}
        permissions:
            contents: read
            packages: write

        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and publish ${{ matrix.tag_suffix }} image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  platforms: ${{ matrix.platform }}
                  push: true
                  tags: |
                      ${{ env.IMAGE_NAME }}:latest-${{ matrix.tag_suffix }}
                      ${{ env.IMAGE_NAME }}:${{ github.sha }}-${{ matrix.tag_suffix }}
                      ${{ env.IMAGE_NAME }}:${{ github.ref_name }}-${{ matrix.tag_suffix }}
                  cache-from: type=gha,scope=${{ matrix.tag_suffix }}
                  cache-to: type=gha,mode=max,scope=${{ matrix.tag_suffix }}
